@endpoint = http://localhost:3000/api

GET {{endpoint}}/jack/control/server

###

POST {{endpoint}}/jack/control/server
Content-Type: application/json

{
  "rate": 96000,
  "period": 128
}

###

DELETE {{endpoint}}/jack/control/server

###

GET {{endpoint}}/alsa/devices

###

POST {{endpoint}}/alsa/load
Content-Type: application/json

{
    "deviceId": "26fcc14bc2ca9f89",
    "client": "zalsa",
    "rate": 96000,
    "period": 128,
    "nperiods": 2
}

###

DELETE {{endpoint}}/alsa/load/26fcc14bc2ca9f89


###

POST {{endpoint}}/alsa/load
Content-Type: application/json

{
    "deviceId": "f63efa817e772803",
    "client": "zalsa",
    "rate": 48000,
    "period": 128,
    "nperiods": 2
}

###

GET {{endpoint}}/jack/ports

###

GET {{endpoint}}/jack/patches

###

POST {{endpoint}}/jack/patches
Content-Type: application/json

{
  "source": {
    "io_type": "in",
    "id": "f63efa817e772803",
    "channel": 1
  },
  "destination": {
    "io_type": "out",
    "id": "26fcc14bc2ca9f89",
    "channel": 1
  }
}

###

DELETE {{endpoint}}/jack/patches
Content-Type: application/json

{
  "source": {
    "io_type": "in",
    "id": "f63efa817e772803",
    "channel": 1
  },
  "destination": {
    "io_type": "out",
    "id": "26fcc14bc2ca9f89",
    "channel": 1
  }
}
